apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-app
  template:
    metadata:
      labels:
        app: brain-app
    spec:
      containers:
      - name: brain-app
        image: 258215414348.dkr.ecr.us-east-1.amazonaws.com/build-app:latest
        ports:
        - containerPort: 80

