apiVersion: v1
kind: Service
metadata:
  name: brain-service
spec:
  type: LoadBalancer
  selector:
    app: brain-app
  ports:
  - port: 3000        # external port (requirement)
    targetPort: 80   # nginx inside container

